### ISSUE TITLE
Examples for NetCDF, HDF4, HDF5, TIFF, and OPeNDAP

### ISSUE THREAD

**Issue by mmccarty** [intake/intake-xarray#5]
A few simple example catalogs for these file types that:

- [ ] Load data
- [ ] Inspect metadata
- [ ] Show a simple plot

**Comment by jhamman** [comment]
xarray also supports backends that access grib, and zarr formats. Examples may want to include those formats as well.

**Comment by martindurant** [comment]
Yes, agree on GRIB (via `PyNIO`) and TIFF should be there too. We may not want to include opendap here, though, since that would need a remote data source.

**Comment by martindurant** [comment]
Except I notice PyNIO still isn't released for py3.

**Comment by jhamman** [comment]
Yes, https://github.com/NCAR/pynio/issues/17 is still lingering. I have been using their dev release of the python3 code and it seems to be working. I wouldn't let this slow you down though. They'll have to get it done by the end of the year because xarray is dropping py2 support then.

**Comment by martindurant** [comment]
@jhamman , is loading via pynio compatible with the chunks= parameter, i.e., using with dask?

**Comment by martindurant** [comment]
(never mind, found a GRIB, tried it, and it works just fine)

**Comment by jhamman** [comment]
What is the status of intake-xarray and open-dap served datasets?

**Comment by martindurant** [comment]
Local files (netcdf, grib, tiff, zarr...) and remote (zarr only) datasets will be totally good.

As of https://github.com/ContinuumIO/intake-xarray/pull/11 , intake should also be able to stream any of these formats, i.e., so that you can read netcdf remotely. The server isn't meant for production, however, and doubtless isn't any kind of performant - it's really meant as POC from a big data point of view.
