### ISSUE TITLE
Q: Possible to rename vars and dims on the fly?

### ISSUE THREAD

**Issue by willirath** [intake/intake-xarray#68]
For datasets that do not follow good naming practices, I'd love to be able to just `cat["entry"].to_dask()` and get a clean dataset.

While all the renaming necessary for this could be done with `preprocess` via xarray keyword args, I wonder if there's a way of just specifying a renaming dict in the catalog.

**Comment by martindurant** [comment]
Does xarray already do this as a loading arg, or are you asking whether intake-xarray can (optionally) perform the [`rename`](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.rename.html)? 
I don't have a huge objection to this, particularly since it is a no-cost operation.

Having said that, Intake has tried to shy away from being a place where data processing happens, and it would be good in general to try to keep to a minimum the number of extra arguments supported by the intake driver.

**Comment by willirath** [comment]
> Does xarray already do this as a loading arg, or are you asking whether intake-xarray can (optionally) perform the rename?

I'm asking wether the latter (performing rename after the loading) is within the scope of intake-xarray. But I fully understand your approach of keeping this as simple as possible.

I guess the solution then is to think about how to do essential post processing in the cleanest way. As this is more of a usage question, I'll move over to stackoverflow.
